### ISSUE TITLE
Is NODE_ENV=development in npm scripts really necessary?

### ISSUE THREAD

**Issue by hgwood** [Zenika/github-insights#17]
The current syntax for en vars in npm scripts is not Windows-compatible. I suggest either remove the env var or use the cross-env package. I can do the PR either way. :)

**Comment by frinyvonnick** [comment]
Good suggestion 👍 A PR would be really appreciated 🙏

**Comment by hgwood** [comment]
Which way do you want to go? Remove `NODE_ENV=development` or add cross-env?

**Comment by frinyvonnick** [comment]
We can remove it since it isn't used in the codebase. If needed later we will add it back with cross-env. Sounds great to you?
